version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/sec
    env_file:
      - ./.env
    ports:
      - '3000:3000'

  my-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mytest05'
      MYSQL_ROOT_PASSWORD: 'roott'
    ports:
      - '3306:3306'
